import React, { useState } from 'react';
import '../src/index.css'; // Import your CSS file

function App() {
  const [content, setContent] = useState(
    <div>
      <h1>Your Music, Your Wealth: Join The SoundMoney Revolution Now!</h1>
      <p>
        Step into a world where your love for music not only enriches your soul 
        but also fills your pockets. Welcome to SoundMoney, where every beat, 
        every note, and every second of your digital consumption becomes a 
        pathway to financial empowerment. This is more than just an opportunity--it's 
        a Revolution waiting for you to join.
      </p>
    </div>
  );

  const showHome = () => {
  window.location.href = '/index.html'; // Navigate to index.html within the public directory
};


  const showAbout = () => {
    setContent(
      <div>
        <h1>YOUR TIME, YOUR MONEY</h1>
        <p>Imagine a world where every moment you spend on your favorite songs and podcasts is valued and rewarded. With SoundMoney's Fan Tokenization, that dream becomes a reality. Every stream, every listen, every engagement earns you tokens, transforming your time into tangible wealth. It's time to reclaim what's rightfully yours—download SoundMoney now and start earning from your passion.</p>
        <h2>Empowerment Through Music</h2>
        <p>Music has the power to move us, inspire us, and unite us. With SoundMoney, that power extends beyond the realm of emotions—it becomes a tool for financial empowerment. By participating in Fan Tokenization, you become an active contributor to the success of your favorite artists, shaping the future of music with every engagement. Your voice matters, your passion matters—join us and be part of something extraordinary.</p>
        <h3>A Fairer Future for All</h3>
        <p>Gone are the days of unfair royalties and exploitative middlemen. SoundMoney's decentralized royalty distribution ensures that artists receive their fair share of the revenue generated by their work. By supporting Fan Tokenization, you're not just earning for yourself—you're championing a more equitable music industry where talent and creativity are valued above all else.</p>
      </div>
    );
  };

  const showInvest = () => {
    setContent(
      <div>
        <h1>INVEST IN SOUNDMONEY NOW</h1>
        <p>Here is some detailed information about investing.</p>
      </div>
    );
  };

  const showMobileApp = () => {
    setContent(
      <div>
        <h1>DOWNLOAD THE MOBILE APP NOW</h1>
        <p>Here is some detailed information about our mobile app.</p>
      </div>
    );
  };

  const showInfluencer = () => {
    setContent(
      <div>
        <h1>JOIN THE INFLUENCER HUB NOW</h1>
        <p>Here is some detailed information about influencers.</p>
      </div>
    );
  };

  return (
    <div>
      <header style={{ backgroundColor: 'aqua' }}>
        <section style={{ background: 'rgb(0, 0, 0)' }}>
          <div>
            <img src="/khf.png" alt="logo" />
            <menu style={{ color: 'white' }}>
              <p> current price (0.003$)</p>
              <button>-</button>
              <p> listing price (1$)</p>
            </menu>
          </div>
        </section>
      </header>
      <div id="background-container" className="background-container">
        <section>
          <div className="button-container">
            <button onClick={showHome}>HOME</button>
            <button onClick={showAbout}>ABOUT</button>
            <button onClick={showInvest}>INVEST</button>
            <button onClick={showMobileApp}>MOBILE APP</button>
            <button onClick={showInfluencer}>INFLUENCER</button>
          </div>
          <div id="main-content">
            {content}
          </div>
        </section>
      </div>
    </div>
  );
}

export default App;
